demo/urls.py
from django.conf.urls import url

from demo.views import ProgramList, ProgramCreate, ProgramUpdate, ProgramDelete

urlpatterns = [
    url('^$', ProgramList.as_view(), name='list'),
    url('^create/$', ProgramCreate.as_view(), name='create'),
    url('^(?P<pk>[0-9]+)/update/$', ProgramUpdate.as_view(), name='update'),
    url('^(?P<pk>[0-9]+)/delete/$', ProgramDelete.as_view(), name='delete'),
]

pyconkr_2017_django_form/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^program/', include('demo.urls', namespace='program')),
    url(r'^program/formview/', include('demo_formview.urls', namespace='program_formview')),
    url(r'^program/generic/', include('demo_generic.urls', namespace='program_generic')),
    url(r'^program/formset/', include('demo_formset.urls', namespace='program_formset')),
    url(r'^program/crispy/', include('demo_crispy.urls', namespace='program_crispy')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block css %}{% endblock css %}
    <title>Pyconkr 2017 - Django Form</title>
</head>
<body style="padding: 15px">
{% block content %}
{% endblock content %}

{% block js %}{% endblock js %}
</body>
</html>

templates/base_bootstrap.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
{% endblock css %}

{% block js %}
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
{% endblock js %}

templates/program_delete.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>"{{ object }}"을(를) 정말 삭제하시겠습니까?</p>
        <input type="submit" value="진행"/>
    </form>
{% endblock content %}

templates/program_form.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="전송"/>
    </form>
{% endblock content %}

templates/program_form_crispy.html
{% extends "base_bootstrap.html" %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block content %}
    {% crispy form %}
{% endblock content %}

templates/program_form_formset.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <form method="post">
        {% csrf_token %}

        <h4>Program</h4>
        {{ form.as_p }}

        <h4>URL</h4>
        {{ formset.management_form }}
        {% for each_form in formset %}
            <p>
                {{ each_form }}
            </p>
        {% endfor %}

        <p>
            <input type="submit" value="전송"/>
            {% if object %}
                <input type="button" value="삭제"
                       onclick="location.href='{% url 'program_formset:delete' object.id %}'"/>
            {% endif %}
        </p>
    </form>
{% endblock content %}

templates/program_form_formview.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="전송"/>
        {% if object %}
            <input type="button" value="삭제" onclick="location.href='{% url 'program_formview:delete' object.id %}'"/>
        {% endif %}
    </form>
{% endblock content %}

templates/program_list.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <ul>
        {% for object in object_list %}
            <li><a href="{% url 'program:update' object.id %}">{{ object }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/program_list_crispy.html
{% extends "base_bootstrap.html" %}
{% load i18n %}


{% block content %}
    <ul>
        {% for object in object_list %}
            <li><a href="{% url 'program_crispy:update' object.id %}">{{ object }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/program_list_formset.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <ul>
        {% for object in object_list %}
            <li><a href="{% url 'program_formset:update' object.id %}">{{ object }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/program_list_formview.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <ul>
        {% for object in object_list %}
            <li><a href="{% url 'program_formview:update' object.id %}">{{ object }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}